# Generated by Django 5.2.8 on 2025-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('message', models.CharField(max_length=255)),
                ('api_name', models.CharField(max_length=100)),
                ('api_type', models.CharField(max_length=100)),
                ('send_data', models.CharField(max_length=100)),
                ('get_data', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log Entry',
                'verbose_name_plural': 'Log Entries',
                'ordering': ['-date_time'],
            },
        ),
    ]
